version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: psql_petapi_dev
    environment:
      POSTGRES_USER: ALAINC00
      POSTGRES_PASSWORD: ROOT1234
      POSTGRES_DB: PET_REGISTER_DB
    ports:
      - "5499:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - petnet

  app:
    build: .
    container_name: mascota_api_app
    ports:
      - "9595:9595"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/PET_REGISTER_DB
      SPRING_DATASOURCE_USERNAME: ALAINC00
      SPRING_DATASOURCE_PASSWORD: ROOT1234
    networks:
      - petnet


volumes:
  postgres_data:

networks:
  petnet:

