version: '3.8'

services:
  postgres:
    container_name: psql_petapi_dev
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: PET_REGISTER_DB
      POSTGRES_USER: ALAINC00
      POSTGRES_PASSWORD: ROOT1234
    ports:
      - "5432:5432"
    networks:
      - petnet

  petapi_app:
    container_name: petapi_app
    image: eclipse-temurin:17-jdk
    depends_on:
      - postgres
    command: ["java", "-jar", "/app/MascotaAPI-0.0.1-SNAPSHOT.jar", "--spring.profiles.active=docker"]
    volumes:
      - ./target/MascotaAPI-0.0.1-SNAPSHOT.jar:/app/MascotaAPI-0.0.1-SNAPSHOT.jar
    ports:
      - "9595:9595"
    networks:
      - petnet

networks:
  petnet:
    driver: bridge
